name: Install Manticore Search on Windows

on:
  push:
    branches:
      - master

jobs:
  install-manticore:
    runs-on: windows-latest
    steps:
      - name: Download Manticore Search installer
        run: |
          Invoke-WebRequest -Uri "https://repo.manticoresearch.com/repository/manticoresearch_windows/release/x64/manticore-13.6.7-25080704-1ab9ccc95-x64.exe" -OutFile "manticore-installer.exe"

      - name: Run Manticore Search installer
        shell: powershell
        run: |
          Start-Process -FilePath .\manticore-installer.exe -ArgumentList '/S' -Wait

      - name: Start Manticore Search manually
        shell: powershell
        run: |
          $searchdPath = "C:\Program Files\Manticore Search\bin\searchd.exe"
          $configPath = "C:\Program Files\Manticore Search\manticore.conf"
          & $searchdPath --config "$configPath"

      - name: Test Manticore connection
        shell: powershell
        run: |
          mysql -h127.0.0.1 -P9306 -e "SHOW TABLES;"
